set nocompatible

call plug#begin()
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'scrooloose/nerdcommenter'
call plug#end()

" Editing
set backspace=indent,eol,start
set hidden
set ruler

" Visual styling
colorscheme tomorrow-night
set colorcolumn=80
set nocursorline
set laststatus=2
set showcmd
set showmode
set wildmenu
set ttyfast
set lazyredraw
set number
set numberwidth=4
set list
let &listchars='tab:▸ ,extends:❯,precedes:❮,nbsp:±'

" Netrw
" let g:netrw_banner=0
" let g:netrw_liststyle=3
" let g:netrw_browse_split=4
" let g:netrw_altv=1
" let g:netrw_winsize=25
" augroup ProjectDrawer
"   autocmd!
"   autocmd VimEnter * :Vexplore
" augroup END

" Searching
set incsearch
set hlsearch
set wrapscan

" Indentation
set autoindent
set expandtab
set shiftround
set shiftwidth=2
set softtabstop=2

" Miscellaneous
set ttimeout
set ttimeoutlen=100
set display=truncate
set scrolloff=5
set sidescrolloff=5
set mouse=a
set nowrap
set splitbelow
set splitright
set listchars+=trail:·
set report=0
set autoread
set synmaxcol=200

" File settings
set backup
set backupdir=$HOME/.vim/files/backup/
set backupext=.vimbackup
set backupskip=
set directory=$HOME/.vim/files/swap//
set updatecount=100
set undofile
set undodir=$HOME/.vim/files/undo/
set viminfo='100,n$HOME/.vim/files/info/viminfo
let g:netrw_home=$HOME.'/vim/files/'

" Syntax highlighting
syntax enable
filetype plugin indent on

" Cursor style
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"

" Mappings
let mapleader = ','
nnoremap ; :
vnoremap ; :
map Q gq
nnoremap <silent> \ :NERDTreeToggle<cr>
nnoremap <silent> <leader>rv :source $MYVIMRC<cr>
nnoremap <leader>S :%s/
vnoremap <leader>S :s/
inoremap kj <esc>
nnoremap <silent> <space> :nohlsearch<Bar>:echo<cr>""
