set nocompatible

call plug#begin()

Plug '$HOME/.fzf'
Plug '/usr/local/opt/fzf'
Plug 'altercation/vim-colors-solarized'
Plug 'christoomey/vim-tmux-navigator'
Plug 'elixir-lang/vim-elixir'
Plug 'fatih/vim-go'
Plug 'jclem/ale'
Plug 'junegunn/fzf.vim'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/gv.vim'
Plug 'junegunn/vim-peekaboo'
Plug 'leafgarland/typescript-vim'
Plug 'mattn/emmet-vim'
Plug 'pangloss/vim-javascript'
Plug 'Quramy/tsuquyomi'
Plug 'rizzatti/dash.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'SirVer/ultisnips'
Plug 'sjl/gundo.vim'
Plug 'slashmili/alchemist.vim'
Plug 'terryma/vim-multiple-cursors'
Plug 'tmux-plugins/vim-tmux-focus-events'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'

call plug#end()

" Editing
set backspace=indent,eol,start
set hidden
set ruler

" Status line
set statusline=%f\ %y\ %h%m%r%w%=%l/%L

" Visual styling
colorscheme solarized
set background=dark
set colorcolumn=80
set guifont=SF\ Mono:h13
set guioptions=
set laststatus=2
set lazyredraw
set linespace=1
set list
set nocursorline
set number
set numberwidth=4
set showcmd
set showmode
set ttyfast
set wildmenu
set fillchars=vert:\ 
let &listchars='tab:▸ ,extends:❯,precedes:❮,nbsp:±'

" Netrw
" let g:netrw_banner=0
" let g:netrw_liststyle=3
" let g:netrw_browse_split=4
" let g:netrw_altv=1
" let g:netrw_winsize=25
" augroup ProjectDrawer
"   autocmd!
"   autocmd VimEnter * :Vexplore
" augroup END

" Searching
set incsearch
set hlsearch
set ignorecase
set smartcase
set wrapscan

" Indentation
set autoindent
set expandtab
set shiftround
set shiftwidth=2
set softtabstop=2
set tabstop=2

" Miscellaneous
set ttimeout
set ttimeoutlen=100
set display=truncate
set scrolloff=5
set sidescrolloff=5
set mouse=a
set wrap
set linebreak
set breakindent
set showbreak=...→\ 
set splitbelow
set splitright
set listchars+=trail:·
set report=0
set autoread
set synmaxcol=200
set dictionary+=/usr/share/dict/words

" File settings
set backup
set backupdir=$HOME/.vim/files/backup/
set backupext=.vimbackup
set backupskip=
set directory=$HOME/.vim/files/swap//
set updatecount=100
set undofile
set undodir=$HOME/.vim/files/undo/
set viminfo='100,n$HOME/.vim/files/info/viminfo
let g:netrw_home=$HOME.'/vim/files/'

" Syntax highlighting
syntax enable
filetype plugin indent on

" Cursor style
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"

" Gundo
let g:gundo_prefer_python3=1
let g:gundo_width=40
let g:gundo_right=1

" vim-javascript
let g:javascript_plugin_jsdoc=1

" NERDCommenter
let g:NERDCommentEmptyLines=1
let g:NERDSpaceDelims=1
let g:NERDTrimTrailingWhitespace=1
let g:NERDDefaultAlign='left'

" NERDTree
let g:NERDTreeNaturalSort=1

" tsuquyomi
let g:tsuquyomi_definition_split=1
let g:tsuquyomi_disable_quickfix=1

" dash.vim
let g:dash_activate=0

" Mappings
let mapleader = ','
nnoremap ; :
vnoremap ; :
map Q gq
nnoremap <silent> \ :NERDTreeToggle<cr>
nnoremap <silent> <leader>vv :source $MYVIMRC<cr>
nnoremap <silent> <leader>vp :source $MYVIMRC<cr> <bar> :PlugInstall<cr>
nnoremap <leader>S :%s/
vnoremap <leader>S :s/
inoremap kj <esc>
nnoremap <silent> <space> :nohlsearch<Bar>:echo<cr>""
nnoremap <silent> <leader>u :GundoToggle<cr>
nnoremap <silent> <leader>gtd :TsuDefinition<cr>
nnoremap <silent> <leader>gtr :TsuReferences<cr>
nnoremap <silent> <leader>gts :TsuSignatureHelp<cr>
nnoremap <silent> <leader>vs :Gstatus<cr>
nmap <silent> <leader>d <Plug>DashSearch

" Vim doesn't do normal escape with Ctrl+C
inoremap <c-c> <esc>

" Window navigation
nnoremap <c-h> <c-w>h
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-l> <c-w>l

" Splits
nnoremap <silent> <leader>\| :vsplit<cr>
nnoremap <silent> <leader>- :split<cr>

" Tabbing
nnoremap <silent> <leader>tt :tabnew<cr>
nnoremap <silent> <leader>tn :tabnext<cr>
nnoremap <silent> <leader>tp :tabprev<cr>
nnoremap <silent> <leader>tc :tabclose<cr>
nnoremap <silent> } :tabnext<cr>
nnoremap <silent> { :tabprev<cr>

" Fuzzy finding
nnoremap <leader>fd :FZF<cr>
nnoremap <leader>fa :Ag<cr>
nnoremap <leader>fb :Buffers<cr>
nnoremap <leader>fl :BLines<cr>
nnoremap <leader>fh :History<cr>
nnoremap <leader>f? :Helptags<cr>
nnoremap <leader>fc :Commands<cr>
nnoremap <leader>fm :Marks<cr>
nnoremap <leader>fs :Snippets<cr>
nnoremap <leader>fg :GFiles?<cr>
nnoremap <leader>fw :Windows<cr>

set exrc
set secure
